language: php

sudo: required

services:
  - docker

compiler:
  - clang
  - g++

before_install:
  - docker-compose run --rm composer require satooshi/php-coveralls

before_script:
  - docker-compose run --rm composer install --prefer-source --dev
  - cd utils/ccat
  - make && make install
  - cd ../../

script: docker-compose run --rm phpunit --coverage-clover ./tests/logs/clover.xml

after_script:
 - docker-compose run cli vendor/bin/php-coveralls -v

notifications:
    on_success: never
    on_failure: always
